In [ ]:
# echo "🎯 开始训练..."
!python3 -m lerobot.scripts.train \
    --dataset.root=./dataset/qnbot_data1 \
    --dataset.repo_id=bradley/qnbot_cherry_transfer_20250705 \
    --policy.type=act \
    --policy.repo_id=bradley/qnbot_cherry_transfer_act \
    --output_dir=outputs/qnbot_cherry_transfer_act \
    --batch_size=16 \
    --steps=100000 \
    --policy.device=cuda \
    --wandb.enable=true \
    --wandb.mode=offline \
    --wandb.project=lerobot_qnbot \
    --wandb.entity=breadlee1024 \
    --wandb.notes="QnBot樱桃传递任务 - 右手拿樱桃玩具传递给左手放到白盘子里" \
    --log_freq=200 \
    --save_freq=10000

In [ ]:
from pathlib import Path

import torch

from lerobot.configs.types import FeatureType
from lerobot.datasets.lerobot_dataset import LeRobotDataset, LeRobotDatasetMetadata
from lerobot.datasets.utils import dataset_to_policy_features
import logging

In [ ]:
# Parameters
FPS = 30
# Dataset parameters
import os
import lerobot

# Get parent directory of the current file

REPO_PATH = os.path.dirname(os.path.dirname(os.path.dirname(lerobot.__file__)))

dataset_root = os.path.join(REPO_PATH, "dataset/qnbot_data1")

repo_id = "bradley/qnbot_cherry_transfer_20250705"
logging.info(f"Using LeRobot repo path: {dataset_root}")

# Create  a directory to sotore the training checkpoints
output_dir = Path("outputs/train/qnbot_cherry_transfer_act")
output_dir.mkdir(parents=True, exist_ok=True)
logging.info(f"Using output directory: {output_dir}")

# Select device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Number of offline training steps (we'll only do offline training for this example.)
# Adjust as you prefer. 5000 steps are needed to get something worth evaluating.
training_steps = 100000
log_freq = 1


In [ ]:
# When starting from scratch (i.e. not from a pretrained policy), we need to specify 2 things before
# creating the policy:
#   - input/output shapes: to properly size the policy
#   - dataset stats: for normalization and denormalization of input/outputs
dataset_metadata = LeRobotDatasetMetadata(repo_id=repo_id, root=dataset_root)
features = dataset_to_policy_features(dataset_metadata.features)
output_features = {key: ft for key, ft in features.items() if ft.type is FeatureType.ACTION}
input_features = {key: ft for key, ft in features.items() if key not in output_features}
from pprint import pformat
print(f"Dataset metadata:\n{pformat(input_features)}")
print(f"Output features:\n{pformat(output_features)}")
logging.info(f"Input features: {input_features}")
logging.info(f"Output features: {output_features}")

Input features: {'observation.state': PolicyFeature(type=<FeatureType.STATE: 'STATE'>, shape=(17,)), 'observation.images.left_wrist': PolicyFeature(type=<FeatureType.VISUAL: 'VISUAL'>, shape=(3, 480, 640)), 'observation.images.head': PolicyFeature(type=<FeatureType.VISUAL: 'VISUAL'>, shape=(3, 480, 640)), 'observation.images.right_wrist': PolicyFeature(type=<FeatureType.VISUAL: 'VISUAL'>, shape=(3, 480, 640))}
Output features: {'action': PolicyFeature(type=<FeatureType.ACTION: 'ACTION'>, shape=(17,))}


In [34]:
# =============================================
# 2. Dataset Setup
# =============================================
from lerobot.policies.diffusion.configuration_diffusion import DiffusionConfig
from lerobot.policies.diffusion.modeling_diffusion import DiffusionPolicy

cfg = DiffusionConfig(input_features=input_features, output_features=output_features)


delta_timestamps = {
    "observation.images.head": [i / dataset_metadata.fps for i in cfg.observation_delta_indices],
    "observation.images.left_wrist": [i / dataset_metadata.fps for i in cfg.observation_delta_indices],
    "observation.images.right_wrist": [i / dataset_metadata.fps for i in cfg.observation_delta_indices],
    "observation.state": [i / dataset_metadata.fps for i in cfg.observation_delta_indices],
    "action": [i / dataset_metadata.fps for i in cfg.action_delta_indices],
}

dataset = LeRobotDataset(
    repo_id=repo_id,
    root=dataset_root,
    delta_timestamps=delta_timestamps
)

# repo_ids = [f"agibotworld/{path.name}" for path in Path(dataset_path).glob("agibotworld/task_*")]
# multi_dataset = MultiLeRobotDataset(
#     repo_ids=repo_ids,
#     root=dataset_path,
#     delta_timestamps=delta_timestamps,
#     local_files_only=True
# )

dataloader = torch.utils.data.DataLoader(
    dataset,
    num_workers=4,
    batch_size=64,
    shuffle=True,
    pin_memory=device.type != "cpu",
    drop_last=True,
)


In [36]:
# =============================================
# 3. Policy Configuration and Initialization
# =============================================
cfg.input_shapes = {
    "observation.images.head": [3, 480, 640],
    "observation.images.left_wrist": [3, 480, 640],
    "observation.images.right_wrist": [3, 480, 640],
    "observation.state": [17],
}
cfg.input_normalization_modes = {
    "observation.images.head": "mean_std",
    "observation.images.left_wrist": "mean_std",
    "observation.images.right_wrist": "mean_std",
    "observation.state": "min_max",
}
cfg.output_shapes = {
    "action": [17],
}


policy = DiffusionPolicy(cfg, dataset_stats=dataset.meta.stats)
#policy = DiffusionPolicy(cfg, dataset_stats=multi_dataset.stats)
policy.train()

policy.to(device)

optimizer = torch.optim.Adam(policy.parameters(), lr=1e-4)

In [37]:

# =============================================
# 4. Training Loop
# =============================================
step = 0
done = False
while not done:
    for batch in dataloader:
        batch = {k: (v.to(device) if isinstance(v, torch.Tensor) else v) for k, v in batch.items()}
        loss, _ = policy.forward(batch)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if step % log_freq == 0:
            print(f"step: {step} loss: {loss.item():.3f}")
        step += 1
        if step >= training_steps:
            done = True
            break

step: 0 loss: 1.204
step: 1 loss: 1.403
step: 2 loss: 1.125
step: 3 loss: 1.057
step: 4 loss: 1.064
step: 5 loss: 1.005
step: 6 loss: 1.015
step: 7 loss: 1.018
step: 8 loss: 1.023
step: 9 loss: 1.025
step: 10 loss: 1.009
step: 11 loss: 1.014
step: 12 loss: 1.016


KeyboardInterrupt: 

In [ ]:
# =============================================
# 5. Save Policy Checkpoint
# =============================================
policy.save_pretrained(output_path)
print(f"Model saved to {output_path}")

In [4]:
from typing import TypedDict
import torch

class QnBotObservation(TypedDict):
    head_image: torch.Tensor  # shape (3, 480, 640)
    left_wrist_image: torch.Tensor  # shape (3, 480, 640)
    right_wrist_image: torch.Tensor  # shape (3, 480, 640)
    state: torch.Tensor  # shape (17,)

# 定义一个函数来处理输入数据并调用策略
def get_action_from_policy(observation: QnBotObservation) -> torch.Tensor:
    # 将输入数据转换为策略所需的格式
    policy_input = {
        "observation.images.head": observation["head_image"].unsqueeze(0),  # 添加batch维度
        "observation.images.left_wrist": observation["left_wrist_image"].unsqueeze(0),
        "observation.images.right_wrist": observation["right_wrist_image"].unsqueeze(0),
        "observation.state": observation["state"].unsqueeze(0),
    }
    
    return policy_input

# 示例用法
observation = QnBotObservation(
    head_image=torch.randn(3, 480, 640),
    left_wrist_image=torch.randn(3, 480, 640),
    right_wrist_image=torch.randn(3, 480, 640),   
    state=torch.randn(17),
)
action = get_action_from_policy(observation)
print(action)

{'observation.images.head': tensor([[[[-1.1578,  2.5514, -0.2521,  ..., -0.4196,  0.4180,  0.7254],
          [ 0.5402, -0.5449, -0.5413,  ..., -0.2494, -0.6972,  0.4624],
          [ 1.5746,  0.3617,  0.6233,  ..., -0.0652,  0.0421, -0.8931],
          ...,
          [ 0.9482,  0.3876,  1.8773,  ..., -0.6471, -0.3681, -1.6418],
          [ 1.5039, -1.6429, -1.1562,  ..., -0.0093,  2.3683, -1.4496],
          [ 1.4184,  0.9086,  1.1185,  ...,  0.2024, -1.4438, -0.2155]],

         [[ 0.0257,  0.2154,  0.2483,  ...,  0.1578,  0.5620,  0.5865],
          [-0.8253,  0.1313,  0.1273,  ...,  0.0744, -0.7674,  1.0903],
          [ 1.5341, -1.3075, -0.7290,  ..., -1.4121, -0.6851,  1.1041],
          ...,
          [ 0.8081,  0.6526, -1.2787,  ...,  0.1970,  1.2633, -0.1823],
          [-0.5749, -0.3297, -0.8452,  ..., -1.4571,  0.0603, -1.3260],
          [-0.2911, -0.9664,  1.6756,  ..., -0.7461,  0.4440, -0.5667]],

         [[ 0.8632,  2.1583,  0.9851,  ..., -2.8637,  0.5418, -0.7831],
  

In [10]:
import torch
# example for torch.cat
a = torch.randn(2, 3)
b = torch.randn(2, 3)
c = torch.cat([a, b], dim=1)  # shape will be (4, 3)
print(c.shape)

# example for torch.stack
a = torch.randn(2, 3)
b = torch.randn(2, 3)
c = torch.stack([a, b], dim=1)  # shape will be (2, 2, 3)
print(c.shape)


torch.Size([2, 6])
torch.Size([2, 2, 3])


In [11]:
def make_att_2d_masks(pad_masks, att_masks):  # see openpi `make_att_2d_masks` (exact copy)
    """Copied from big_vision.

    Tokens can attend to valid inputs tokens which have a cumulative mask_ar
    smaller or equal to theirs. This way `mask_ar` int[B, N] can be used to
    setup several types of attention, for example:

      [[1 1 1 1 1 1]]: pure causal attention.

      [[0 0 0 1 1 1]]: prefix-lm attention. The first 3 tokens can attend between
          themselves and the last 3 tokens have a causal attention. The first
          entry could also be a 1 without changing behaviour.

      [[1 0 1 0 1 0 0 1 0 0]]: causal attention between 4 blocks. Tokens of a
          block can attend all previous blocks and all tokens on the same block.

    Args:
      input_mask: bool[B, N] true if its part of the input, false if padding.
      mask_ar: int32[B, N] mask that's 1 where previous tokens cannot depend on
        it and 0 where it shares the same attention mask as the previous token.
    """
    if att_masks.ndim != 2:
        raise ValueError(att_masks.ndim)
    if pad_masks.ndim != 2:
        raise ValueError(pad_masks.ndim)

    cumsum = torch.cumsum(att_masks, dim=1)
    print(f"cumsum: {cumsum}")
    att_2d_masks = cumsum[:, None, :] <= cumsum[:, :, None]
    print(f"att_2d_masks: {att_2d_masks}")
    pad_2d_masks = pad_masks[:, None, :] * pad_masks[:, :, None]
    print(f"pad_2d_masks: {pad_2d_masks}")
    return att_2d_masks & pad_2d_masks
# Example usage
pad_masks = torch.tensor([[1, 1, 1, 0, 0], [1, 1, 0, 0, 0]], dtype=torch.bool)
att_masks = torch.tensor([[0, 0, 1, 1, 1], [0, 1, 1, 1, 1]], dtype=torch.bool)
att_2d_masks = make_att_2d_masks(pad_masks, att_masks)
print(att_2d_masks.shape)  # should be (B, N, N)

cumsum: tensor([[0, 0, 1, 2, 3],
        [0, 1, 2, 3, 4]])
att_2d_masks: tensor([[[ True,  True, False, False, False],
         [ True,  True, False, False, False],
         [ True,  True,  True, False, False],
         [ True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True]],

        [[ True, False, False, False, False],
         [ True,  True, False, False, False],
         [ True,  True,  True, False, False],
         [ True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True]]])
pad_2d_masks: tensor([[[ True,  True,  True, False, False],
         [ True,  True,  True, False, False],
         [ True,  True,  True, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[ True,  True, False, False, False],
         [ True,  True, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, Fa